### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by lemonness** [NormanBB/WJX_Autosubmit#1]
您好，想问下 使用您的那个代码报错了

  File "f:/interseting programs/AUTO wjx/main.py", line 133, in main
    if int(result) in [10]:
ValueError: invalid literal for int() with base 10: '9〒'
是什么原因呢

**Comment by NormanBB** [comment]
这种情况是我没有对除“10”，“22”以外的结果进行处理。但你应该只是偶尔出现这种情况吧？重新运行程序问题解决了吗？可以把程序运行记录贴上来看看。

**Comment by lemonness** [comment]
![image](https://user-images.githubusercontent.com/47708347/63209364-5750dc80-c112-11e9-8d0d-bb0e5518478c.png)
您帮我看一看

**Comment by NormanBB** [comment]
具体原因应该是，读取问卷星返回的响应时，出现了“10”，“22”以外的返回结果。你想看看整个响应可以在124行，result不用切片，直接`result = r.text`。

而规避你这种情况，你可以试试，将124行`result = r.text[0:2]`，改为`result = r.text[0:1]`，然后133行`if int(result) in [10]`改为`if int(result) in [1]`，然后再次运行。

**Comment by lemonness** [comment]
修改以后能成功跑起来了，但是response的值只有2和9，是提交失败的。
想问下 ，是不是因为问卷的题型所导致的呢。

**Comment by NormanBB** [comment]
你把问卷链接贴出来看看

**Comment by lemonness** [comment]
https://www.wjx.cn/jq/40741412.aspx

**Comment by NormanBB** [comment]
目前初步观察，你的问卷涉及，当某个问题选中某个选项时，则关联问题出现或消失（不知道这样你能不能理解），这导致了提交数据会形成

`1$2}2$1}3$2}4$1}5$3}6$4}7$2}8$3}9$-3}10$-3}11$5}12$1}13$1}14$2}15$4}16$1`

的形式，注意其中的第九题和第十题中的答案类型，目前脚本未能对应所有的问卷类型。但如果你如果是作为问卷的发布者可以修改选项的话，建议修改成固定的问题。如果你有空进一步完善脚本的话，欢迎提交pull request ，如果没空的话也可以和我说一声。

**Comment by lemonness** [comment]
明白了  非常感谢 ！！！我刚才还想问是不是这个原因造成的。我非常乐意帮您完善脚本，但作为初学者，还有很多地方不太清楚，不知道您是否要求有期限，因为本人还需要更加深入的学习这一块的内容。

**Comment by NormanBB** [comment]
我并不要求期限，而且个人目前精力不在这个项目上。我也是看着那几个参考项目然后弄出来这个项目的，建议看看那些参考项目，特别是简书的。如果你研究过程中有疑问，可以发邮件到我的邮箱`15920548078@163.com`。

期待你的pull request. 
 ####  :)

**Comment by lemonness** [comment]
好的 再次感谢
