### ISSUE TITLE
脚本运行失败

### ISSUE THREAD

**Issue by littlematch59** [NormanBB/WJX_Autosubmit#10]
2020.9.07
依赖安装好之后运行脚本，总是出现以下报错：
WJX_Autosubmit-master>python WJX_Autosubmit.py -l

        本程序用于构建随机答案填写问卷星问卷

use proxy from www.proxy-list.download
开始验证代理
验证代理完成，用时： 0.53 s
使用验证proxy-list代理
输入问卷地址:https://www.wjx.cn/m/90368218.aspx
输入提交次数:20
程序开始运行
Traceback (most recent call last):
  File "WJX_Autosubmit.py", line 235, in <module>
    main(times)
  File "WJX_Autosubmit.py", line 155, in main
    ip_list = proxy.choose_proxy(filename)
  File "D:\Users\小火柴\Desktop\问卷星\WJX_Autosubmit-master\fake_info.py", line 58, in choose_proxy
    with open(filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'proxy_list_temp.list'

**Comment by littlematch59** [comment]
感谢回答，但是我也试过了jq格式的问卷，脚本报错问题还是一样，请问是否是WJX脚本发生了改动？能否邮件发一份WJX脚本。谢谢~






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NormanBB/WJX_Autosubmit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月7日(星期一) 晚上9:55
收件人:&nbsp;"NormanBB/WJX_Autosubmit"<WJX_Autosubmit@noreply.github.com&gt;;
抄送:&nbsp;"littlematch"<1282626975@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NormanBB/WJX_Autosubmit] 脚本运行失败 (#10)





 
这里的问题是程序未适配m模式的问卷。请使用类似 https://www.wjx.cn/jq/88459848.aspx 的jq模式问卷。

**Comment by NormanBB** [comment]
@littlematch59 请参见以上说的问题二。在GitHub issue中查看。

**Comment by NormanBB** [comment]
同时可使用我给出的问卷地址来验证程序可用性。目前程序未进行大更新，旧程序依旧可用。

**Comment by littlematch59** [comment]
用代理运行程序的意思是先开个梯子再运行脚本吗？

**Comment by NormanBB** [comment]
> 用代理运行程序的意思是先开个梯子再运行脚本吗？

是的。

**Comment by littlematch59** [comment]
按照以上条件来运行程序(已经换了博主刚更新的check.py脚本)，现在程序可以运行，但是结果显示成功提交0份。

**Comment by NormanBB** [comment]
> 按照以上条件来运行程序(已经换了博主刚更新的check.py脚本)，现在程序可以运行，但是结果显示成功提交0份。

1. 使用proxy-list的代理。

2. 运行多次，比如20次。
