### ISSUE TITLE
请问强制多选有解决办法吗

### ISSUE THREAD

**Issue by JoeKingdom** [NormanBB/WJX_Autosubmit#11]
![屏幕截图 2020-11-24 214601](https://user-images.githubusercontent.com/29192924/100102281-57f02b00-2e9e-11eb-9ffe-4f2de3dde804.jpg)

**Comment by NormanBB** [comment]
错误 1 ：未使用代理。解决方法见README。

目前项目问题，就算使用了代理，也无法保证代理可用。我自己跑了一遍，没有有效提交。

如果你说的是需要某个问题指定多个答案，可自行研究。我觉得简单的方法是加入条件判断。

**Comment by JoeKingdom** [comment]
多谢老哥，代理没问题可以运行的。就是这个多选的问题，我看了您在已关闭提问里面的回复，正在自己琢磨
