### ISSUE TITLE
已经挂了

### ISSUE THREAD

**Issue by jakewilliamsonuk** [NormanBB/WJX_Autosubmit#12]
use proxy from www.proxy-list.download
开始验证代理
验证代理完成，用时： 17.91 s
使用验证proxy-list代理
输入问卷地址:
输入提交次数:30
程序开始运行
代理 159.8.114.37:80 不可用
代理 119.81.189.194:8123 不可用
代理 69.28.62.166:3128 不可用
代理 119.81.189.194:80 不可用
代理 169.57.157.148:8123 不可用
代理 159.8.114.34:8123 不可用
代理 159.8.114.37:8123 不可用
代理 169.57.157.148:80 不可用
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
代理 169.57.157.146:8123 不可用
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
[ Response : 22 ]  ===> 提交失败！！！！
程序运行结束，成功提交0份调查报告

**Comment by NormanBB** [comment]
了解。但短期内不会更新。

**Comment by nadersidc** [comment]
已更新 需要联系VX  reverseEn 另外提供dy ks协议
