### ISSUE TITLE
代理ip后的验证码问题

### ISSUE THREAD

**Issue by WROIATE** [NormanBB/WJX_Autosubmit#2]
脚本刚开始有效，当使用成功了5次后出现了验证要求，很郁闷不知道为啥，ip代理看后台之前提交记录应该是对的，不知道为啥突然要验证了，返回信息如下
![Snipaste_2019-10-30_10-50-11](https://user-images.githubusercontent.com/44677306/67825049-11959480-fb03-11e9-93aa-5189d1641a29.png)

**Comment by WROIATE** [comment]
更新一下好像是整个问卷都要验证码了。。。不管ip是啥

**Comment by NormanBB** [comment]
有可能是问卷自身设置了需要填写验证码，也可能是问卷星更新了机制。你可以把问卷链接贴出来看看。

**Comment by WROIATE** [comment]
这是链接:https://www.wjx.cn/jq/46678759.aspx

**Comment by NormanBB** [comment]
问卷内容不错。

我第一次点击也需要验证码，验证码的问题比较难解决。但你作为发布者不能把验证关闭？

**Comment by WROIATE** [comment]
> 问卷内容不错。
> 
> 我第一次点击也需要验证码，验证码的问题比较难解决。但你作为发布者不能把验证关闭？

我在问卷星里已经把限制给关了。。。但不知道为啥还是有

![Snipaste_2019-10-31_09-52-22](https://user-images.githubusercontent.com/44677306/67912205-284ff000-fbc4-11e9-8ccd-f46a4c94bbbf.png)

**Comment by NormanBB** [comment]
我发现你的问卷会有一个提示

![批注 2019-10-31 172003](https://user-images.githubusercontent.com/18748504/67934347-b34fdb00-fc02-11e9-95e8-7a3cb4b5c1bb.jpg)

会不会是账号问题？

也有人说

> 你的问卷如果设置红包或者添加了投票题型，就会自动出现验证码的

**Comment by WROIATE** [comment]
![Snipaste_2019-10-31_19-20-46](https://user-images.githubusercontent.com/44677306/67942971-0716f000-fc14-11e9-9469-051545c95ede.png)
> 我发现你的问卷会有一个提示
> 
> ![批注 2019-10-31 172003](https://user-images.githubusercontent.com/18748504/67934347-b34fdb00-fc02-11e9-95e8-7a3cb4b5c1bb.jpg)
> 
> 会不会是账号问题？
> 
> 也有人说
> 
> > 你的问卷如果设置红包或者添加了投票题型，就会自动出现验证码的
我和客服沟通了一下，可能是探查出是爬虫了，不知道是不是答题时间问题

![Snipaste_2019-10-31_19-05-07](https://user-images.githubusercontent.com/44677306/67942953-ff574b80-fc13-11e9-98e5-b91188e3cd0c.png)

![Snipaste_2019-10-31_19-20-46](https://user-images.githubusercontent.com/44677306/67943066-3f1e3300-fc14-11e9-8001-bdb8b56aaec4.png)

**Comment by WROIATE** [comment]
> 我发现你的问卷会有一个提示
> 
> ![批注 2019-10-31 172003](https://user-images.githubusercontent.com/18748504/67934347-b34fdb00-fc02-11e9-95e8-7a3cb4b5c1bb.jpg)
> 
> 会不会是账号问题？
> 
> 也有人说
> 
> > 你的问卷如果设置红包或者添加了投票题型，就会自动出现验证码的



我和客服沟通了一下，可能是检测出是爬虫了，不知道是不是答题时间原因

![Snipaste_2019-10-31_19-05-07](https://user-images.githubusercontent.com/44677306/67943169-742a8580-fc14-11e9-9648-4cd24ba46c35.png)

![Snipaste_2019-10-31_19-20-46](https://user-images.githubusercontent.com/44677306/67943184-7bea2a00-fc14-11e9-924c-3965021f5e87.png)

**Comment by NormanBB** [comment]
十分抱歉出现这样的情况。

可调整脚本设置尝试跳过验证。

若成功可考虑提交pull

**Comment by WROIATE** [comment]
> 十分抱歉出现这样的情况。
> 
> 可调整脚本设置尝试跳过验证。
> 
> 若成功可考虑提交pull

ok，谢谢啦
