### ISSUE TITLE
默认答案——多选题

### ISSUE THREAD

**Issue by Chenmo1212** [NormanBB/WJX_Autosubmit#4]
请问一下，如果我想设置多选题的默认答案，应该如何修改您的代码呢？

**Comment by NormanBB** [comment]
https://github.com/tignioj/test_login/tree/master/wjx

参考这个，我readme中放错链接了

**Comment by NormanBB** [comment]
至于说你想自己实现多选题的选择，你在读完代码后会发现，有一个answer list，对list做长度判断可以甄别多选题，而最后post的答案构造可以通过chrome分析可以得到格式。
