### ISSUE TITLE
关于get_fill_content()函数的一点修改与建议

### ISSUE THREAD

**Issue by nublast** [NormanBB/WJX_Autosubmit#5]
今天我测试了一下这个脚本发现还是可以用的，我是提交固定答案所以没有测试随机选择的功能，在测试过程中发现get_fill_content()函数中的 res = requests.get(url, headers=headers)有时会丢失与服务器的链接而导致程序意外停止，所以做了一点修改如下：
def get_fill_content(url):
    headers = {
    'user-agent': UserAgent().random
    }
    res=None
    while res is None:
        try:
            res = requests.get(url, headers=headers,timeout=5)
        except:
            pass
    cookies = res.cookies
    return res.text,cookies
经测试稳定很多，不会出现意外停止了

**Comment by NormanBB** [comment]
非常感谢对代码的建议，可提交pr 来 merge。

**:)**
