### ISSUE TITLE
WJX_Autosubmit.py 提交后都是同一个ip

### ISSUE THREAD

**Issue by kingui1106** [NormanBB/WJX_Autosubmit#7]
是这样子的吗，看代码不是有代理吗

**Comment by NormanBB** [comment]
请使用最新版程序。

请贴出目前程序运行结果。
可在程序中加入print(proxy) 来显示代理IP。

**Comment by kingui1106** [comment]
程序开始运行
111.206.37.100:80
[ Response : 10 ]  ===> 提交成功！！！！
112.80.248.75:80
[ Response : 10 ]  ===> 提交成功！！！！
182.61.62.23:80
[ Response : 10 ]  ===> 提交成功！！！！
221.182.31.54:8080
[ Response : 10 ]  ===> 提交成功！！！！
111.13.100.91:80
[ Response : 10 ]  ===> 提交成功！！！！
程序运行结束，成功提交5份调查报告

在[问卷星后台](https://imgchr.com/i/aHIegI)看到的都是我自己电脑的ip

**Comment by NormanBB** [comment]
https://www.wjx.cn/jq/43178556.aspx

使用我的链接试试。

**Comment by NormanBB** [comment]
我这边也已复现相同结果，看看先。

**Comment by NormanBB** [comment]
解决方案，在POST时使用HTTPS代理。但我找到的解决方案成功率并不高，目前在40%左右。

目前我并不急着推更新，如果你有更好的解决方案可以继续交流。

参考：https://github.com/fate0/getproxy

**Comment by kingui1106** [comment]
可以试一下芝麻代理，每天都有免费的
http://h.zhimaruanjian.com/getapi/

**Comment by NormanBB** [comment]
如果你有可用版本，可以提交PR。

我试用了一下，效果对我来说不理想。注册完账号之后还收到了客服的电话，亲切的询问了使用状况。这对我来说，并不认同这样的做法。

我宁愿用GitHub上的公开代理。
